## Creating the dataset

### Imports

In [43]:
import pandas as pd

### Reading the datasets

In [44]:
df_benign = pd.read_csv('../Datasets/features_extraidas_benignas.csv')
df_malign = pd.read_csv('../Datasets/features_extraidas_malignas.csv')

In [45]:
df_benign.head()

,filename,sha256,num_sections,has_rsrc_section,max_entropy,avg_entropy,total_imports,suspicious_api_count,timestamp,is_dll,image_size,is_64bit
0,avast.exe,6f486a9d30bc410250a27bd1b1a5b95518c70bf29be93e...,6,1,6.673007,4.746518,185,11,1726818470,0,258048,0
1,Windows_Credentials_Viewer.exe,501a946121cf6dc612f9ba078067392ef8c4f2f78adf79...,5,1,7.007302,5.728303,674,16,1496170115,0,4804608,0
2,RiotClientCrashHandler.exe,d224446bc4aed018940fe1a13e5bab2e6b98769199a612...,6,0,6.328385,4.244157,191,9,2396255610,0,917504,1
3,RiotClientFoundation.dll,8cf741ffcd8b2492219be0e00cc8db23e11b669615b48c...,7,1,6.636638,4.958194,440,17,380415491,1,16805888,1
4,RiotClientServices.exe,76282276fcaad1118c3eff19d5802747e035fe57bcd03e...,7,1,7.997690,5.343996,380,12,3586101223,0,74416128,1

In [46]:
df_malign.head()

,filename,sha256,num_sections,has_rsrc_section,max_entropy,avg_entropy,total_imports,suspicious_api_count,timestamp,is_dll,image_size,is_64bit
0,cerber.exe,e67834d1e8b38ec5864cfa101b140aeaba8f1900a6e269...,4,1,6.553434,4.741731,317,13,1495658914,0,630784,0
1,cryptowall.bin,45317968759d3e37282ceb75149f627d648534c5b4685f...,4,1,6.521482,5.077275,183,5,1421137545,0,54423552,0
2,ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439...,ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439...,4,1,7.999868,6.380856,114,7,1290243905,0,3514368,0
3,Ransom.Xdata.exe,f0103528b96533db9d76df0f760b4d0ffc1a142b0070e3...,5,1,7.255816,6.645420,2,0,1415348819,0,270336,0
4,Ransom (17.06.05) .exe,dcf5da82c4785d8cca8f4d4478bebbf4ff7af25e584ee6...,5,1,7.255816,6.211749,2,0,1415348819,0,94208,0

### Formating the datasets

In [47]:
df_malign["is_ransomware"] = 1
df_benign["is_ransomware"] = 0

In [50]:
df = pd.concat([df_benign,df_malign]).reset_index(drop=True)
df

,filename,sha256,num_sections,has_rsrc_section,max_entropy,avg_entropy,total_imports,suspicious_api_count,timestamp,is_dll,image_size,is_64bit,is_ransomware
0,avast.exe,6f486a9d30bc410250a27bd1b1a5b95518c70bf29be93e...,6,1,6.673007,4.746518,185,11,1726818470,0,258048,0,0
1,Windows_Credentials_Viewer.exe,501a946121cf6dc612f9ba078067392ef8c4f2f78adf79...,5,1,7.007302,5.728303,674,16,1496170115,0,4804608,0,0
2,RiotClientCrashHandler.exe,d224446bc4aed018940fe1a13e5bab2e6b98769199a612...,6,0,6.328385,4.244157,191,9,2396255610,0,917504,1,0
3,RiotClientFoundation.dll,8cf741ffcd8b2492219be0e00cc8db23e11b669615b48c...,7,1,6.636638,4.958194,440,17,380415491,1,16805888,1,0
4,RiotClientServices.exe,76282276fcaad1118c3eff19d5802747e035fe57bcd03e...,7,1,7.997690,5.343996,380,12,3586101223,0,74416128,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120,2280898cb29faf1785e782596d8029cb471537ec38352e...,2280898cb29faf1785e782596d8029cb471537ec38352e...,3,0,7.670983,6.526161,0,0,3632400331,0,86016,0,1
121,b5b105751a2bf965a6b78eeff100fe4c75282ad6f37f98...,b5b105751a2bf965a6b78eeff100fe4c75282ad6f37f98...,3,0,7.666354,6.524618,0,0,3632400331,0,86016,0,1
122,c75748dc544629a8a5d08c0d8ba7fda3508a3efdaed905...,c75748dc544629a8a5d08c0d8ba7fda3508a3efdaed905...,3,0,7.669562,6.525688,0,0,3632400331,0,86016,0,1
123,ccd6a495dfb2c5e26cd65e34c9569615428801e01fd89e...,ccd6a495dfb2c5e26cd65e34c9569615428801e01fd89e...,4,1,7.113736,5.604225,138,3,1484836636,0,417792,0,1
124,e75717be1633b5e3602827dc3b5788ff691dd325b0eddd...,e75717be1633b5e3602827dc3b5788ff691dd325b0eddd...,3,0,7.669009,6.525503,0,0,3632400331,0,86016,0,1

### Exporting the df

In [51]:
df.to_csv('../Datasets/dataset_ransomware_v1.csv')